#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xd29ace7d, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf6823bf5, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0x24e050a5, __VMLINUX_SYMBOL_STR(drm_prime_gem_destroy) },
	{ 0x19987fca, __VMLINUX_SYMBOL_STR(drm_fb_helper_set_par) },
	{ 0xfd6d346, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x8adadc83, __VMLINUX_SYMBOL_STR(drm_crtc_helper_set_config) },
	{ 0xbea18ba4, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x3986c90f, __VMLINUX_SYMBOL_STR(drm_gem_put_pages) },
	{ 0xffc30f45, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x750b181b, __VMLINUX_SYMBOL_STR(drm_fb_helper_initial_config) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x44b1c7de, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xb8787f3c, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_release) },
	{ 0x8fd93405, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0x8c2ea85f, __VMLINUX_SYMBOL_STR(drm_unplug_dev) },
	{ 0x1a2190f, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xae5f716a, __VMLINUX_SYMBOL_STR(drm_fb_helper_unlink_fbi) },
	{ 0xea54c357, __VMLINUX_SYMBOL_STR(dma_buf_detach) },
	{ 0x2f2c2cd5, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_leave) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0x398f4814, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xd5152710, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x4675e27, __VMLINUX_SYMBOL_STR(drm_gem_free_mmap_offset) },
	{ 0x2162d9c8, __VMLINUX_SYMBOL_STR(drm_vblank_cleanup) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x2f1f8f20, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x2da4c1b7, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x9114d0da, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0xf9a7e28b, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0xf76b0a59, __VMLINUX_SYMBOL_STR(read_current_timer) },
	{ 0xb75e7dad, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0x57482400, __VMLINUX_SYMBOL_STR(drm_fb_helper_unregister_fbi) },
	{ 0x1bf3e656, __VMLINUX_SYMBOL_STR(dma_buf_vunmap) },
	{ 0xd29fa2df, __VMLINUX_SYMBOL_STR(usb_get_descriptor) },
	{ 0xfe309b48, __VMLINUX_SYMBOL_STR(drm_fb_helper_pan_display) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x4ca716ee, __VMLINUX_SYMBOL_STR(drm_helper_connector_dpms) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x5b5120db, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x3744cf36, __VMLINUX_SYMBOL_STR(vmalloc_to_pfn) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xc0a91e5f, __VMLINUX_SYMBOL_STR(drm_prime_pages_to_sg) },
	{ 0xfd638a03, __VMLINUX_SYMBOL_STR(usb_deregister) },
	{ 0x423f0aae, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0xbf3e4fec, __VMLINUX_SYMBOL_STR(drm_helper_mode_fill_fb_struct) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x4daf3366, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x37490319, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0xe736b961, __VMLINUX_SYMBOL_STR(vmap) },
	{ 0x901f177d, __VMLINUX_SYMBOL_STR(dma_buf_put) },
	{ 0xd65a1e99, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_var) },
	{ 0xfacd2e14, __VMLINUX_SYMBOL_STR(pgprot_user) },
	{ 0x9adc66c, __VMLINUX_SYMBOL_STR(usb_control_msg) },
	{ 0x9138e27f, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x3e2705d6, __VMLINUX_SYMBOL_STR(drm_gem_object_release) },
	{ 0xdb38325f, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0x2639d553, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xbfa4f89e, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0xb337b54a, __VMLINUX_SYMBOL_STR(drm_fb_helper_release_fbi) },
	{ 0xc46c5628, __VMLINUX_SYMBOL_STR(dma_buf_unmap_attachment) },
	{ 0xb3345f81, __VMLINUX_SYMBOL_STR(usb_free_coherent) },
	{ 0x4957abb5, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x76662f13, __VMLINUX_SYMBOL_STR(drm_fb_helper_prepare) },
	{ 0x3f8d96e, __VMLINUX_SYMBOL_STR(drm_gem_vm_open) },
	{ 0x6a6db5b2, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x6e01c636, __VMLINUX_SYMBOL_STR(vm_insert_page) },
	{ 0xd7099d8, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0xcdd158d, __VMLINUX_SYMBOL_STR(sg_alloc_table) },
	{ 0x1977e977, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x74c664ae, __VMLINUX_SYMBOL_STR(dma_buf_begin_cpu_access) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0x5e7a1184, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xcdc0f145, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_imageblit) },
	{ 0x5fbea82, __VMLINUX_SYMBOL_STR(usb_submit_urb) },
	{ 0x3d6e1757, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0xee120393, __VMLINUX_SYMBOL_STR(dma_buf_map_attachment) },
	{ 0xbbafc34d, __VMLINUX_SYMBOL_STR(drm_gem_dmabuf_export) },
	{ 0xbc9068df, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0xd1f60e20, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0xcd291efc, __VMLINUX_SYMBOL_STR(drm_fb_helper_check_var) },
	{ 0x595048c7, __VMLINUX_SYMBOL_STR(drm_fb_helper_blank) },
	{ 0x394e5013, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x5cc36e08, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0xf6f5580, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x3caaafc2, __VMLINUX_SYMBOL_STR(drm_fb_helper_alloc_fbi) },
	{ 0x5e6664fc, __VMLINUX_SYMBOL_STR(drm_crtc_init) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x6721b2bf, __VMLINUX_SYMBOL_STR(dma_buf_attach) },
	{ 0x51887ced, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0x6d37e1d, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0xd2d6ec6, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x6733ac14, __VMLINUX_SYMBOL_STR(drm_gem_object_init) },
	{ 0x8e3c9ac8, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x3ec905b5, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x85b0a272, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x551b5e24, __VMLINUX_SYMBOL_STR(drm_gem_create_mmap_offset) },
	{ 0xc47d890d, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x404e0bcf, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x94961283, __VMLINUX_SYMBOL_STR(vunmap) },
	{ 0x8e58db22, __VMLINUX_SYMBOL_STR(remap_pfn_range) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x22b961a5, __VMLINUX_SYMBOL_STR(drm_fb_helper_deferred_io) },
	{ 0x4df15ae2, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0xe135f7aa, __VMLINUX_SYMBOL_STR(usb_register_driver) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0x47efac06, __VMLINUX_SYMBOL_STR(drm_fb_helper_fini) },
	{ 0x557b3957, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x9cd60539, __VMLINUX_SYMBOL_STR(sg_free_table) },
	{ 0x3e884f4b, __VMLINUX_SYMBOL_STR(vm_get_page_prot) },
	{ 0x43ce1a4c, __VMLINUX_SYMBOL_STR(drm_prime_sg_to_page_addr_arrays) },
	{ 0xc383d1b2, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_fillrect) },
	{ 0x78f84f7b, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0xe8d4a706, __VMLINUX_SYMBOL_STR(drm_helper_disable_unused_functions) },
	{ 0xc74dcbca, __VMLINUX_SYMBOL_STR(dma_buf_end_cpu_access) },
	{ 0x104dec1e, __VMLINUX_SYMBOL_STR(drm_fb_helper_setcmap) },
	{ 0xca4ad5b, __VMLINUX_SYMBOL_STR(usb_alloc_coherent) },
	{ 0x4baa1c9a, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x98ead08a, __VMLINUX_SYMBOL_STR(dma_buf_vmap) },
	{ 0xef976afa, __VMLINUX_SYMBOL_STR(drm_fb_helper_sys_copyarea) },
	{ 0x101f20f3, __VMLINUX_SYMBOL_STR(drm_gem_get_pages) },
	{ 0x4a63a659, __VMLINUX_SYMBOL_STR(drm_fb_helper_fill_fix) },
	{ 0x902c766a, __VMLINUX_SYMBOL_STR(drm_connector_register) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x2b6a2531, __VMLINUX_SYMBOL_STR(usb_free_urb) },
	{ 0x837d0f0a, __VMLINUX_SYMBOL_STR(down_timeout) },
	{ 0x32ec9ee6, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_disable) },
	{ 0x3cadc8c8, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x97cd2862, __VMLINUX_SYMBOL_STR(drm_fb_helper_debug_enter) },
	{ 0xe0329b37, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0x490ba919, __VMLINUX_SYMBOL_STR(drm_fb_helper_init) },
	{ 0x42def0c8, __VMLINUX_SYMBOL_STR(drm_fb_helper_single_add_all_connectors) },
	{ 0xde10e87b, __VMLINUX_SYMBOL_STR(usb_alloc_urb) },
	{ 0xcd244727, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x78f5c8d0, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper";

MODULE_ALIAS("usb:v17E9p*d*dc*dsc*dp*icFFisc00ip00in*");

MODULE_INFO(srcversion, "387506B4BB73A28702CD9B7");
