#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xd29ace7d, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x92b57248, __VMLINUX_SYMBOL_STR(flush_work) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0x2689dbe0, __VMLINUX_SYMBOL_STR(drm_edid_get_monitor_name) },
	{ 0xe537c040, __VMLINUX_SYMBOL_STR(drm_atomic_get_connector_state) },
	{ 0xfd6d346, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x18e7e9a1, __VMLINUX_SYMBOL_STR(drm_atomic_legacy_backoff) },
	{ 0xfd60df2, __VMLINUX_SYMBOL_STR(drm_get_connector_status_name) },
	{ 0xe88ed9a6, __VMLINUX_SYMBOL_STR(drm_calc_timestamping_constants) },
	{ 0x2627b818, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x91fec1cc, __VMLINUX_SYMBOL_STR(drm_rect_calc_vscale) },
	{ 0x3924dd56, __VMLINUX_SYMBOL_STR(try_wait_for_completion) },
	{ 0x349cba85, __VMLINUX_SYMBOL_STR(strchr) },
	{ 0x80a7fd1e, __VMLINUX_SYMBOL_STR(drm_atomic_nonblocking_commit) },
	{ 0x44b1c7de, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xad535a28, __VMLINUX_SYMBOL_STR(drm_bridge_disable) },
	{ 0x2310ebbc, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0xe32d6648, __VMLINUX_SYMBOL_STR(drm_mode_create_from_cmdline_mode) },
	{ 0x97255bdf, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x4189eef0, __VMLINUX_SYMBOL_STR(framebuffer_release) },
	{ 0xd9f0d5ae, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0xd35f75a1, __VMLINUX_SYMBOL_STR(match_string) },
	{ 0x56c5dc12, __VMLINUX_SYMBOL_STR(drm_modeset_drop_locks) },
	{ 0xc9827427, __VMLINUX_SYMBOL_STR(drm_bridge_pre_enable) },
	{ 0x6f4ee142, __VMLINUX_SYMBOL_STR(unlink_framebuffer) },
	{ 0x2c289b44, __VMLINUX_SYMBOL_STR(drm_property_create_blob) },
	{ 0x90e40232, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xa3f3129b, __VMLINUX_SYMBOL_STR(drm_atomic_state_clear) },
	{ 0xd3dbfbc4, __VMLINUX_SYMBOL_STR(_find_first_zero_bit_le) },
	{ 0x1a2190f, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0x5afb03c8, __VMLINUX_SYMBOL_STR(drm_bridge_attach) },
	{ 0xb26e8434, __VMLINUX_SYMBOL_STR(drm_mode_destroy) },
	{ 0xd4c14632, __VMLINUX_SYMBOL_STR(system_unbound_wq) },
	{ 0xdc8d1ea1, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x4d974b9c, __VMLINUX_SYMBOL_STR(register_sysrq_key) },
	{ 0x4bdd5b02, __VMLINUX_SYMBOL_STR(i2c_transfer) },
	{ 0xc9144d77, __VMLINUX_SYMBOL_STR(drm_atomic_get_plane_state) },
	{ 0x96a4f490, __VMLINUX_SYMBOL_STR(fb_sys_read) },
	{ 0xf1421d13, __VMLINUX_SYMBOL_STR(drm_mode_sort) },
	{ 0xb396095e, __VMLINUX_SYMBOL_STR(drm_modeset_backoff) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0xed51e6, __VMLINUX_SYMBOL_STR(fence_wait_timeout) },
	{ 0x508db8e3, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0x987c11c7, __VMLINUX_SYMBOL_STR(__pv_phys_pfn_offset) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x46bf7332, __VMLINUX_SYMBOL_STR(cfb_fillrect) },
	{ 0xb909bbd, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0xa0744ea9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x2f1f8f20, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xffd627f3, __VMLINUX_SYMBOL_STR(drm_plane_force_disable) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0x2622141c, __VMLINUX_SYMBOL_STR(platform_device_register_full) },
	{ 0xf9a7e28b, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x11f47eae, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_fini) },
	{ 0xbb7b56, __VMLINUX_SYMBOL_STR(drm_object_property_set_value) },
	{ 0x5f2d1a7c, __VMLINUX_SYMBOL_STR(sys_copyarea) },
	{ 0x54db5cbc, __VMLINUX_SYMBOL_STR(drm_mode_validate_basic) },
	{ 0x37e74642, __VMLINUX_SYMBOL_STR(get_jiffies_64) },
	{ 0xffc6c87a, __VMLINUX_SYMBOL_STR(drm_detect_monitor_audio) },
	{ 0xc499ae1e, __VMLINUX_SYMBOL_STR(kstrdup) },
	{ 0xf26005a, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0x28f95139, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_prop_for_crtc) },
	{ 0xc2e8ee7a, __VMLINUX_SYMBOL_STR(i2c_add_adapter) },
	{ 0x728cb178, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0x131db64a, __VMLINUX_SYMBOL_STR(system_long_wq) },
	{ 0x1baf3817, __VMLINUX_SYMBOL_STR(param_ops_string) },
	{ 0x4e49aeca, __VMLINUX_SYMBOL_STR(drm_atomic_set_mode_for_crtc) },
	{ 0x81f3afb, __VMLINUX_SYMBOL_STR(complete_all) },
	{ 0xee4bd35a, __VMLINUX_SYMBOL_STR(fb_set_suspend) },
	{ 0xc631580a, __VMLINUX_SYMBOL_STR(console_unlock) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xcb2340b8, __VMLINUX_SYMBOL_STR(drm_rect_debug_print) },
	{ 0xd2335101, __VMLINUX_SYMBOL_STR(drm_fb_get_bpp_depth) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x59ef50f0, __VMLINUX_SYMBOL_STR(drm_edid_block_valid) },
	{ 0xdd0a2ba2, __VMLINUX_SYMBOL_STR(strlcat) },
	{ 0x74dcb1d7, __VMLINUX_SYMBOL_STR(drm_mode_object_reference) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0x817c065b, __VMLINUX_SYMBOL_STR(drm_bridge_post_disable) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x81a125ef, __VMLINUX_SYMBOL_STR(drm_atomic_crtc_set_property) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x5b5120db, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x15036f45, __VMLINUX_SYMBOL_STR(drm_atomic_state_alloc) },
	{ 0x9bdfdeca, __VMLINUX_SYMBOL_STR(fb_deferred_io_mmap) },
	{ 0x12be2088, __VMLINUX_SYMBOL_STR(drm_mode_copy) },
	{ 0x86c2ccbf, __VMLINUX_SYMBOL_STR(drm_atomic_commit) },
	{ 0xd331df51, __VMLINUX_SYMBOL_STR(drm_mode_find_dmt) },
	{ 0xe40cf67f, __VMLINUX_SYMBOL_STR(cfb_imageblit) },
	{ 0x9a18d7ff, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xea234fe3, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x71736b78, __VMLINUX_SYMBOL_STR(drm_bridge_enable) },
	{ 0x423f0aae, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0xf090eadf, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xf9fbab03, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x7a890c8, __VMLINUX_SYMBOL_STR(fb_alloc_cmap) },
	{ 0x811a6b4b, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0x71c90087, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x6e30ba8e, __VMLINUX_SYMBOL_STR(drm_rect_rotate_inv) },
	{ 0xa79c7633, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_connector) },
	{ 0x4daf3366, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0xf892f2a5, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0x6d1ecf69, __VMLINUX_SYMBOL_STR(drm_atomic_plane_set_property) },
	{ 0x39b06be9, __VMLINUX_SYMBOL_STR(drm_property_unreference_blob) },
	{ 0x962805c3, __VMLINUX_SYMBOL_STR(register_framebuffer) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x84b183ae, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xfbaaf01e, __VMLINUX_SYMBOL_STR(console_lock) },
	{ 0x73e20c1c, __VMLINUX_SYMBOL_STR(strlcpy) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x9138e27f, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xbf067e8d, __VMLINUX_SYMBOL_STR(drm_bridge_detach) },
	{ 0xd6ac7a50, __VMLINUX_SYMBOL_STR(drm_modeset_legacy_acquire_ctx) },
	{ 0xbfa4f89e, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0xf0442a7c, __VMLINUX_SYMBOL_STR(platform_device_unregister) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x9107371d, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x8fac51f1, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all_ctx) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x622598b1, __VMLINUX_SYMBOL_STR(init_wait_entry) },
	{ 0x6a6db5b2, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x19e8ceff, __VMLINUX_SYMBOL_STR(drm_modeset_lock) },
	{ 0x20645642, __VMLINUX_SYMBOL_STR(drm_debug) },
	{ 0xdd447148, __VMLINUX_SYMBOL_STR(drm_mode_validate_size) },
	{ 0xe034227a, __VMLINUX_SYMBOL_STR(drm_crtc_wait_one_vblank) },
	{ 0x9b339219, __VMLINUX_SYMBOL_STR(drm_crtc_get_hv_timing) },
	{ 0x4201fd35, __VMLINUX_SYMBOL_STR(drm_mode_connector_list_update) },
	{ 0x9c7edef3, __VMLINUX_SYMBOL_STR(drm_atomic_get_crtc_state) },
	{ 0x98b71c6, __VMLINUX_SYMBOL_STR(fb_dealloc_cmap) },
	{ 0x4059792f, __VMLINUX_SYMBOL_STR(print_hex_dump) },
	{ 0x13656c22, __VMLINUX_SYMBOL_STR(i2c_del_adapter) },
	{ 0xf9b33408, __VMLINUX_SYMBOL_STR(drm_dev_printk) },
	{ 0xd1ced500, __VMLINUX_SYMBOL_STR(drm_mode_set_crtcinfo) },
	{ 0xe6a4851e, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0xb1c3a01a, __VMLINUX_SYMBOL_STR(oops_in_progress) },
	{ 0xfe382870, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x922255, __VMLINUX_SYMBOL_STR(drm_mode_prune_invalid) },
	{ 0x14fd1aa2, __VMLINUX_SYMBOL_STR(drm_atomic_set_crtc_for_plane) },
	{ 0x12a38747, __VMLINUX_SYMBOL_STR(usleep_range) },
	{ 0x3f46f79, __VMLINUX_SYMBOL_STR(sys_fillrect) },
	{ 0x40d04664, __VMLINUX_SYMBOL_STR(console_trylock) },
	{ 0xbc9068df, __VMLINUX_SYMBOL_STR(drm_framebuffer_unregister_private) },
	{ 0x85d472aa, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x59aa14cf, __VMLINUX_SYMBOL_STR(fence_release) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0xba8bb333, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0xc0095ff6, __VMLINUX_SYMBOL_STR(sys_imageblit) },
	{ 0xb053adda, __VMLINUX_SYMBOL_STR(drm_rect_rotate) },
	{ 0x9f7696f9, __VMLINUX_SYMBOL_STR(drm_sysfs_hotplug_event) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0x9accfd59, __VMLINUX_SYMBOL_STR(fb_sys_write) },
	{ 0x4c5d5a95, __VMLINUX_SYMBOL_STR(drm_mode_debug_printmodeline) },
	{ 0x6c6cdd4d, __VMLINUX_SYMBOL_STR(wait_for_completion_interruptible_timeout) },
	{ 0xcf04fdfa, __VMLINUX_SYMBOL_STR(drm_bridge_mode_fixup) },
	{ 0x5cc36e08, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x399362ec, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x9df7dbd9, __VMLINUX_SYMBOL_STR(drm_add_modes_noedid) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0x4eebc3d7, __VMLINUX_SYMBOL_STR(drm_atomic_connector_set_property) },
	{ 0xf6f5580, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x990cdf26, __VMLINUX_SYMBOL_STR(drm_warn_on_modeset_not_all_locked) },
	{ 0x2d136d1d, __VMLINUX_SYMBOL_STR(drm_crtc_commit_put) },
	{ 0x3a974318, __VMLINUX_SYMBOL_STR(drm_atomic_clean_old_fb) },
	{ 0x2fa5914, __VMLINUX_SYMBOL_STR(drm_gem_cma_describe) },
	{ 0x5a647323, __VMLINUX_SYMBOL_STR(drm_modeset_acquire_init) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x8e3c9ac8, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x53ce4035, __VMLINUX_SYMBOL_STR(framebuffer_alloc) },
	{ 0x344b7739, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x3ec905b5, __VMLINUX_SYMBOL_STR(fb_deferred_io_cleanup) },
	{ 0x79765e3f, __VMLINUX_SYMBOL_STR(drm_mode_set_config_internal) },
	{ 0x85b0a272, __VMLINUX_SYMBOL_STR(fb_deferred_io_init) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xc47d890d, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0xa28078b2, __VMLINUX_SYMBOL_STR(drm_edid_duplicate) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x6900d335, __VMLINUX_SYMBOL_STR(drm_rect_clip_scaled) },
	{ 0x2256fafa, __VMLINUX_SYMBOL_STR(div64_u64_rem) },
	{ 0xe9b2ee32, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0x68e2b935, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x557b3957, __VMLINUX_SYMBOL_STR(drm_modeset_lock_all) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1f6572ee, __VMLINUX_SYMBOL_STR(dma_common_mmap) },
	{ 0x16fc5e7f, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_count) },
	{ 0x2d50570f, __VMLINUX_SYMBOL_STR(drm_rect_calc_hscale) },
	{ 0x1a660637, __VMLINUX_SYMBOL_STR(cfb_copyarea) },
	{ 0xebca62a9, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_connectors) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x7785729, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb81960ca, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0x78f84f7b, __VMLINUX_SYMBOL_STR(drm_modeset_unlock_all) },
	{ 0x6a2aeaac, __VMLINUX_SYMBOL_STR(drm_bridge_mode_set) },
	{ 0x6533eb8f, __VMLINUX_SYMBOL_STR(drm_mode_plane_set_obj_prop) },
	{ 0xdc345313, __VMLINUX_SYMBOL_STR(drm_atomic_add_affected_planes) },
	{ 0x4baa1c9a, __VMLINUX_SYMBOL_STR(drm_framebuffer_init) },
	{ 0x1bd67c94, __VMLINUX_SYMBOL_STR(drm_mode_connector_set_tile_property) },
	{ 0x49ebacbd, __VMLINUX_SYMBOL_STR(_clear_bit) },
	{ 0x7cf9099, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0xae715e3c, __VMLINUX_SYMBOL_STR(drm_mode_object_unreference) },
	{ 0xcbc9557f, __VMLINUX_SYMBOL_STR(unregister_sysrq_key) },
	{ 0x3ac1fef9, __VMLINUX_SYMBOL_STR(drm_mode_legacy_fb_format) },
	{ 0x3cadc8c8, __VMLINUX_SYMBOL_STR(drm_mode_object_find) },
	{ 0x617f2cb2, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0xe31a8ee0, __VMLINUX_SYMBOL_STR(drm_mode_vrefresh) },
	{ 0xc7ba311c, __VMLINUX_SYMBOL_STR(drm_property_reference_blob) },
	{ 0x78f5c8d0, __VMLINUX_SYMBOL_STR(drm_framebuffer_cleanup) },
	{ 0x4dce1fb2, __VMLINUX_SYMBOL_STR(unregister_framebuffer) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,fb_sys_fops,syscopyarea,sysfillrect,sysimgblt";


MODULE_INFO(srcversion, "0019D9D7FC8630ACD067CED");
