#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0xd29ace7d, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xb077e70a, __VMLINUX_SYMBOL_STR(clk_unprepare) },
	{ 0x3ce4ca6f, __VMLINUX_SYMBOL_STR(disable_irq) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xdc56f5c9, __VMLINUX_SYMBOL_STR(drm_gem_prime_export) },
	{ 0xce102fc0, __VMLINUX_SYMBOL_STR(rpi_firmware_transaction) },
	{ 0xf6823bf5, __VMLINUX_SYMBOL_STR(drm_release) },
	{ 0xfd6d346, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x12da5bb2, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x92bf4e99, __VMLINUX_SYMBOL_STR(__pm_runtime_idle) },
	{ 0xbea18ba4, __VMLINUX_SYMBOL_STR(drm_dev_register) },
	{ 0x815588a6, __VMLINUX_SYMBOL_STR(clk_enable) },
	{ 0x7e2eb572, __VMLINUX_SYMBOL_STR(of_find_i2c_adapter_by_node) },
	{ 0x2627b818, __VMLINUX_SYMBOL_STR(drm_get_edid) },
	{ 0x47439a66, __VMLINUX_SYMBOL_STR(drm_atomic_helper_update_plane) },
	{ 0xccc64e49, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_duplicate_state) },
	{ 0x180e823, __VMLINUX_SYMBOL_STR(__pm_runtime_disable) },
	{ 0x52b69f52, __VMLINUX_SYMBOL_STR(drm_calc_vbltimestamp_from_scanoutpos) },
	{ 0xffc30f45, __VMLINUX_SYMBOL_STR(drm_dev_alloc) },
	{ 0x44e887bc, __VMLINUX_SYMBOL_STR(component_unbind_all) },
	{ 0x7aa1756e, __VMLINUX_SYMBOL_STR(kvfree) },
	{ 0x8ea69e7, __VMLINUX_SYMBOL_STR(mipi_dsi_packet_format_is_long) },
	{ 0x2e5810c6, __VMLINUX_SYMBOL_STR(__aeabi_unwind_cpp_pr1) },
	{ 0xb8eec98b, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x2310ebbc, __VMLINUX_SYMBOL_STR(drm_edid_to_eld) },
	{ 0x90eea5aa, __VMLINUX_SYMBOL_STR(__pm_runtime_use_autosuspend) },
	{ 0xd9f0d5ae, __VMLINUX_SYMBOL_STR(drm_gem_cma_create) },
	{ 0x8de13715, __VMLINUX_SYMBOL_STR(drm_format_vert_chroma_subsampling) },
	{ 0x8a7dafd3, __VMLINUX_SYMBOL_STR(clk_fixed_factor_ops) },
	{ 0x8fd93405, __VMLINUX_SYMBOL_STR(drm_mode_config_cleanup) },
	{ 0xef448676, __VMLINUX_SYMBOL_STR(component_add) },
	{ 0x172f021e, __VMLINUX_SYMBOL_STR(__pm_runtime_suspend) },
	{ 0x3dd3f751, __VMLINUX_SYMBOL_STR(of_parse_phandle) },
	{ 0x90e40232, __VMLINUX_SYMBOL_STR(drm_mode_config_reset) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x633c200c, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_reset) },
	{ 0x1a2190f, __VMLINUX_SYMBOL_STR(arm_dma_ops) },
	{ 0xdf4d40d4, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_mmap) },
	{ 0xe0640a14, __VMLINUX_SYMBOL_STR(drm_atomic_helper_page_flip) },
	{ 0x4f632761, __VMLINUX_SYMBOL_STR(devm_snd_dmaengine_pcm_register) },
	{ 0x3a1c5ba4, __VMLINUX_SYMBOL_STR(drm_match_cea_mode) },
	{ 0x5cc509a4, __VMLINUX_SYMBOL_STR(nsecs_to_jiffies) },
	{ 0xb7fbf419, __VMLINUX_SYMBOL_STR(drm_atomic_helper_swap_state) },
	{ 0xb6e6d99d, __VMLINUX_SYMBOL_STR(clk_disable) },
	{ 0xe056c9b9, __VMLINUX_SYMBOL_STR(drm_cvt_mode) },
	{ 0x5ef22123, __VMLINUX_SYMBOL_STR(drm_crtc_handle_vblank) },
	{ 0x3d9835a6, __VMLINUX_SYMBOL_STR(gpio_to_desc) },
	{ 0x1afae5e7, __VMLINUX_SYMBOL_STR(down_interruptible) },
	{ 0x398f4814, __VMLINUX_SYMBOL_STR(drm_helper_probe_single_connector_modes) },
	{ 0x508db8e3, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x4f21f449, __VMLINUX_SYMBOL_STR(mipi_dsi_host_unregister) },
	{ 0xdedccaa2, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_off) },
	{ 0x4205ad24, __VMLINUX_SYMBOL_STR(cancel_work_sync) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0x20625400, __VMLINUX_SYMBOL_STR(platform_bus_type) },
	{ 0xed4ca7e4, __VMLINUX_SYMBOL_STR(component_bind_all) },
	{ 0xe2fae716, __VMLINUX_SYMBOL_STR(kmemdup) },
	{ 0xe097b66, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_init) },
	{ 0xce7e9c8b, __VMLINUX_SYMBOL_STR(devm_ioremap_resource) },
	{ 0xb1ad28e0, __VMLINUX_SYMBOL_STR(__gnu_mcount_nc) },
	{ 0x36fdda67, __VMLINUX_SYMBOL_STR(hdmi_infoframe_pack) },
	{ 0x8fdf772a, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x28cc25db, __VMLINUX_SYMBOL_STR(arm_copy_from_user) },
	{ 0x2f1f8f20, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x9d6aebfd, __VMLINUX_SYMBOL_STR(component_match_add_release) },
	{ 0x61205d2a, __VMLINUX_SYMBOL_STR(drm_vblank_no_hw_counter) },
	{ 0xc29548a6, __VMLINUX_SYMBOL_STR(__pm_runtime_resume) },
	{ 0x63150e06, __VMLINUX_SYMBOL_STR(clk_get_parent) },
	{ 0x4daeadc5, __VMLINUX_SYMBOL_STR(trace_event_buffer_reserve) },
	{ 0x2da4c1b7, __VMLINUX_SYMBOL_STR(drm_dev_unref) },
	{ 0x9114d0da, __VMLINUX_SYMBOL_STR(drm_vblank_init) },
	{ 0x4b738af7, __VMLINUX_SYMBOL_STR(component_master_del) },
	{ 0xca45efbc, __VMLINUX_SYMBOL_STR(drm_format_horz_chroma_subsampling) },
	{ 0xf9a7e28b, __VMLINUX_SYMBOL_STR(drm_encoder_init) },
	{ 0x4620f7f7, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_get_sg_table) },
	{ 0x556e4390, __VMLINUX_SYMBOL_STR(clk_get_rate) },
	{ 0xfa4d8db1, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_crtc_destroy_state) },
	{ 0xc61eb554, __VMLINUX_SYMBOL_STR(snd_pcm_hw_constraint_eld) },
	{ 0x7a43ee09, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_reset) },
	{ 0xf26005a, __VMLINUX_SYMBOL_STR(drm_universal_plane_init) },
	{ 0xf9422afd, __VMLINUX_SYMBOL_STR(__platform_driver_register) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x480f307c, __VMLINUX_SYMBOL_STR(drm_gem_cma_vm_ops) },
	{ 0xb75e7dad, __VMLINUX_SYMBOL_STR(drm_connector_cleanup) },
	{ 0xf4fa543b, __VMLINUX_SYMBOL_STR(arm_copy_to_user) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0x32807b60, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_duplicate_state) },
	{ 0x422de701, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_duplicate_state) },
	{ 0x66e5ae4c, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_crtc_duplicate_state) },
	{ 0x275ef902, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfe72de1e, __VMLINUX_SYMBOL_STR(drm_atomic_helper_set_config) },
	{ 0xe707d823, __VMLINUX_SYMBOL_STR(__aeabi_uidiv) },
	{ 0x74dcb1d7, __VMLINUX_SYMBOL_STR(drm_mode_object_reference) },
	{ 0x88ab6fe3, __VMLINUX_SYMBOL_STR(kgdb_active) },
	{ 0xfa2a45e, __VMLINUX_SYMBOL_STR(__memzero) },
	{ 0x5264fe60, __VMLINUX_SYMBOL_STR(trace_define_field) },
	{ 0xb2fa4edd, __VMLINUX_SYMBOL_STR(drm_mm_init) },
	{ 0x5f754e5a, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x5b5120db, __VMLINUX_SYMBOL_STR(drm_mode_connector_attach_encoder) },
	{ 0x385082a1, __VMLINUX_SYMBOL_STR(drm_irq_install) },
	{ 0x6d28e6a, __VMLINUX_SYMBOL_STR(of_clk_src_onecell_get) },
	{ 0x17628b39, __VMLINUX_SYMBOL_STR(devm_clk_register) },
	{ 0x429be6d3, __VMLINUX_SYMBOL_STR(remove_conflicting_framebuffers) },
	{ 0xcc337fd5, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_restore_mode) },
	{ 0x9a18d7ff, __VMLINUX_SYMBOL_STR(dev_err) },
	{ 0x51d559d1, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0xea234fe3, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_put) },
	{ 0x423f0aae, __VMLINUX_SYMBOL_STR(drm_gem_object_unreference_unlocked) },
	{ 0xf090eadf, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x9019b072, __VMLINUX_SYMBOL_STR(drm_object_attach_property) },
	{ 0xda826aac, __VMLINUX_SYMBOL_STR(drm_atomic_helper_prepare_planes) },
	{ 0xf9fbab03, __VMLINUX_SYMBOL_STR(drm_mode_duplicate) },
	{ 0x58dbd784, __VMLINUX_SYMBOL_STR(drm_mode_create_tv_properties) },
	{ 0x811a6b4b, __VMLINUX_SYMBOL_STR(drm_crtc_init_with_planes) },
	{ 0xff771bd, __VMLINUX_SYMBOL_STR(__cpu_online_mask) },
	{ 0xc56a93bb, __VMLINUX_SYMBOL_STR(drm_put_dev) },
	{ 0x6e39938a, __VMLINUX_SYMBOL_STR(of_graph_get_next_endpoint) },
	{ 0x44b17ae7, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_reset) },
	{ 0x3e9d3734, __VMLINUX_SYMBOL_STR(of_find_property) },
	{ 0x4daf3366, __VMLINUX_SYMBOL_STR(drm_gem_handle_create) },
	{ 0x37490319, __VMLINUX_SYMBOL_STR(drm_gem_dumb_destroy) },
	{ 0xb7a7ddcb, __VMLINUX_SYMBOL_STR(snd_dmaengine_pcm_prepare_slave_config) },
	{ 0x8e934020, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_on) },
	{ 0xf892f2a5, __VMLINUX_SYMBOL_STR(drm_atomic_state_free) },
	{ 0x9aebc20b, __VMLINUX_SYMBOL_STR(dma_sync_wait) },
	{ 0x6e08e2ee, __VMLINUX_SYMBOL_STR(drm_fb_cma_get_gem_obj) },
	{ 0xf7a3cd9a, __VMLINUX_SYMBOL_STR(trace_event_reg) },
	{ 0x4ba9df60, __VMLINUX_SYMBOL_STR(drm_panel_attach) },
	{ 0xb2c912af, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_hotplug_event) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x9138e27f, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x3b6dc75, __VMLINUX_SYMBOL_STR(drm_probe_ddc) },
	{ 0x4a2ea2f7, __VMLINUX_SYMBOL_STR(drm_fb_cma_create) },
	{ 0xf03e0c5e, __VMLINUX_SYMBOL_STR(platform_get_resource) },
	{ 0xdb38325f, __VMLINUX_SYMBOL_STR(drm_read) },
	{ 0xe792eaf5, __VMLINUX_SYMBOL_STR(drm_mm_insert_node_generic) },
	{ 0x2639d553, __VMLINUX_SYMBOL_STR(noop_llseek) },
	{ 0xfa5bcf35, __VMLINUX_SYMBOL_STR(mod_timer) },
	{ 0xbfa4f89e, __VMLINUX_SYMBOL_STR(drm_add_edid_modes) },
	{ 0x4b06494d, __VMLINUX_SYMBOL_STR(of_clk_add_provider) },
	{ 0x658a8e1c, __VMLINUX_SYMBOL_STR(dma_request_chan_by_mask) },
	{ 0x75696d0a, __VMLINUX_SYMBOL_STR(snd_soc_unregister_card) },
	{ 0x8e865d3c, __VMLINUX_SYMBOL_STR(arm_delay_ops) },
	{ 0x70b81619, __VMLINUX_SYMBOL_STR(bus_find_device) },
	{ 0x9107371d, __VMLINUX_SYMBOL_STR(drm_atomic_set_fb_for_plane) },
	{ 0x41482d8b, __VMLINUX_SYMBOL_STR(strndup_user) },
	{ 0xf4e97b1a, __VMLINUX_SYMBOL_STR(rpi_firmware_property) },
	{ 0xb9d1f4f2, __VMLINUX_SYMBOL_STR(drm_debugfs_create_files) },
	{ 0x1c54897b, __VMLINUX_SYMBOL_STR(perf_trace_run_bpf_submit) },
	{ 0xaaecf75d, __VMLINUX_SYMBOL_STR(perf_trace_buf_alloc) },
	{ 0x4957abb5, __VMLINUX_SYMBOL_STR(drm_connector_init) },
	{ 0x5f9712da, __VMLINUX_SYMBOL_STR(of_match_device) },
	{ 0x2196324, __VMLINUX_SYMBOL_STR(__aeabi_idiv) },
	{ 0x6a6db5b2, __VMLINUX_SYMBOL_STR(drm_mode_connector_update_edid_property) },
	{ 0x870d8e9a, __VMLINUX_SYMBOL_STR(dma_alloc_from_coherent) },
	{ 0x59e5070d, __VMLINUX_SYMBOL_STR(__do_div64) },
	{ 0xd7099d8, __VMLINUX_SYMBOL_STR(drm_gem_vm_close) },
	{ 0x1977e977, __VMLINUX_SYMBOL_STR(drm_gem_prime_fd_to_handle) },
	{ 0x7abd3727, __VMLINUX_SYMBOL_STR(of_get_address) },
	{ 0x18866f31, __VMLINUX_SYMBOL_STR(drm_plane_helper_disable) },
	{ 0xbcdef571, __VMLINUX_SYMBOL_STR(gpiod_get_raw_value_cansleep) },
	{ 0xe6a4851e, __VMLINUX_SYMBOL_STR(drm_plane_cleanup) },
	{ 0xf3207539, __VMLINUX_SYMBOL_STR(drm_printk) },
	{ 0x5e7a1184, __VMLINUX_SYMBOL_STR(drm_ioctl) },
	{ 0xbb483857, __VMLINUX_SYMBOL_STR(drm_gem_prime_import) },
	{ 0x3d6e1757, __VMLINUX_SYMBOL_STR(drm_gem_mmap) },
	{ 0xf4f5c448, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_duplicate_state) },
	{ 0xb5684e29, __VMLINUX_SYMBOL_STR(idr_find_slowpath) },
	{ 0xe256f84, __VMLINUX_SYMBOL_STR(drm_atomic_helper_wait_for_vblanks) },
	{ 0x821c8566, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_destroy_state) },
	{ 0x2e1d69a, __VMLINUX_SYMBOL_STR(__drm_atomic_helper_plane_destroy_state) },
	{ 0x5cbed3b2, __VMLINUX_SYMBOL_STR(pm_runtime_enable) },
	{ 0xa5319c5, __VMLINUX_SYMBOL_STR(trace_event_ignore_this_pid) },
	{ 0x638d3ae, __VMLINUX_SYMBOL_STR(drm_atomic_helper_check) },
	{ 0xd1f60e20, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x6a561756, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vunmap) },
	{ 0xd62c833f, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0xf4a1c237, __VMLINUX_SYMBOL_STR(drm_irq_uninstall) },
	{ 0x38a4f7ae, __VMLINUX_SYMBOL_STR(drm_format_num_planes) },
	{ 0x7c9a7371, __VMLINUX_SYMBOL_STR(clk_prepare) },
	{ 0x2b741c86, __VMLINUX_SYMBOL_STR(devm_snd_soc_register_component) },
	{ 0xdbf6729e, __VMLINUX_SYMBOL_STR(__pm_runtime_set_status) },
	{ 0xe71e013a, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_disables) },
	{ 0x394e5013, __VMLINUX_SYMBOL_STR(drm_crtc_send_vblank_event) },
	{ 0x50fad434, __VMLINUX_SYMBOL_STR(round_jiffies_up) },
	{ 0x5cc36e08, __VMLINUX_SYMBOL_STR(drm_gem_object_lookup) },
	{ 0x399362ec, __VMLINUX_SYMBOL_STR(drm_crtc_vblank_get) },
	{ 0x149259a, __VMLINUX_SYMBOL_STR(of_get_named_gpio_flags) },
	{ 0xbc8fc952, __VMLINUX_SYMBOL_STR(trace_event_buffer_commit) },
	{ 0x7f24de73, __VMLINUX_SYMBOL_STR(jiffies_to_usecs) },
	{ 0x3b9d009a, __VMLINUX_SYMBOL_STR(drm_format_plane_cpp) },
	{ 0x8c211eeb, __VMLINUX_SYMBOL_STR(devm_clk_get) },
	{ 0xf6f5580, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x1a770ac3, __VMLINUX_SYMBOL_STR(drm_detect_hdmi_monitor) },
	{ 0x9c0bd51f, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x429d71d0, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_set_property) },
	{ 0x598542b2, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xb0a68e97, __VMLINUX_SYMBOL_STR(snd_soc_unregister_codec) },
	{ 0x44e2df58, __VMLINUX_SYMBOL_STR(drm_atomic_helper_connector_dpms) },
	{ 0x51887ced, __VMLINUX_SYMBOL_STR(drm_gem_prime_handle_to_fd) },
	{ 0xef0ce39f, __VMLINUX_SYMBOL_STR(rpi_firmware_get) },
	{ 0x76d9b876, __VMLINUX_SYMBOL_STR(clk_set_rate) },
	{ 0x26b3e5de, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_import_sg_table) },
	{ 0xd85cd67e, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x5e701a0e, __VMLINUX_SYMBOL_STR(event_triggers_call) },
	{ 0xd2d6ec6, __VMLINUX_SYMBOL_STR(drm_connector_unregister) },
	{ 0x8e3c9ac8, __VMLINUX_SYMBOL_STR(drm_encoder_cleanup) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x332cebcf, __VMLINUX_SYMBOL_STR(of_graph_get_remote_port_parent) },
	{ 0xc47d890d, __VMLINUX_SYMBOL_STR(drm_crtc_cleanup) },
	{ 0x3cfcde0e, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_planes) },
	{ 0xfcec0987, __VMLINUX_SYMBOL_STR(enable_irq) },
	{ 0x28d6861d, __VMLINUX_SYMBOL_STR(__vmalloc) },
	{ 0x32a1fea, __VMLINUX_SYMBOL_STR(drm_atomic_helper_crtc_destroy_state) },
	{ 0x404e0bcf, __VMLINUX_SYMBOL_STR(drm_mode_config_init) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x451e1706, __VMLINUX_SYMBOL_STR(drm_helper_hpd_irq_event) },
	{ 0xefe7b39e, __VMLINUX_SYMBOL_STR(drm_hdmi_avi_infoframe_from_display_mode) },
	{ 0xfa876c3e, __VMLINUX_SYMBOL_STR(component_del) },
	{ 0x9d669763, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x67fe08fd, __VMLINUX_SYMBOL_STR(trace_event_raw_init) },
	{ 0x499cb58c, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x84ef8ff1, __VMLINUX_SYMBOL_STR(drm_panel_detach) },
	{ 0x4be7fb63, __VMLINUX_SYMBOL_STR(up) },
	{ 0xe9b2ee32, __VMLINUX_SYMBOL_STR(drm_mode_equal) },
	{ 0xb79ec15d, __VMLINUX_SYMBOL_STR(mipi_dsi_create_packet) },
	{ 0x5fd96b71, __VMLINUX_SYMBOL_STR(drm_atomic_helper_cleanup_planes) },
	{ 0x74c134b9, __VMLINUX_SYMBOL_STR(__sw_hweight32) },
	{ 0x1db7dc40, __VMLINUX_SYMBOL_STR(pgprot_kernel) },
	{ 0xf5c2d34d, __VMLINUX_SYMBOL_STR(hdmi_audio_infoframe_init) },
	{ 0xeb953a9e, __VMLINUX_SYMBOL_STR(drm_debugfs_remove_files) },
	{ 0xc83fa618, __VMLINUX_SYMBOL_STR(drm_mm_takedown) },
	{ 0x1cfb04fa, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1f6572ee, __VMLINUX_SYMBOL_STR(dma_common_mmap) },
	{ 0xb745243f, __VMLINUX_SYMBOL_STR(pm_runtime_set_autosuspend_delay) },
	{ 0xc13c4b03, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xbbbd5b65, __VMLINUX_SYMBOL_STR(drm_atomic_helper_disable_plane) },
	{ 0x8f0da45, __VMLINUX_SYMBOL_STR(trace_raw_output_prep) },
	{ 0x676bbc0f, __VMLINUX_SYMBOL_STR(_set_bit) },
	{ 0x7785729, __VMLINUX_SYMBOL_STR(drm_mode_probed_add) },
	{ 0xc0025dfa, __VMLINUX_SYMBOL_STR(component_master_add_with_match) },
	{ 0xb2d48a2e, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0xb0a0da0c, __VMLINUX_SYMBOL_STR(rational_best_approximation) },
	{ 0xd4669fad, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x1148b623, __VMLINUX_SYMBOL_STR(drm_fbdev_cma_fini) },
	{ 0xf147dcb2, __VMLINUX_SYMBOL_STR(hdmi_spd_infoframe_init) },
	{ 0xd54a0557, __VMLINUX_SYMBOL_STR(platform_get_irq) },
	{ 0x3c93ea25, __VMLINUX_SYMBOL_STR(trace_seq_printf) },
	{ 0xae0b77f6, __VMLINUX_SYMBOL_STR(of_drm_find_panel) },
	{ 0x530d79a8, __VMLINUX_SYMBOL_STR(platform_driver_unregister) },
	{ 0x7a29a3fa, __VMLINUX_SYMBOL_STR(drm_mm_remove_node) },
	{ 0x3b969839, __VMLINUX_SYMBOL_STR(drm_kms_helper_poll_init) },
	{ 0x1ae55e6f, __VMLINUX_SYMBOL_STR(drm_gem_cma_free_object) },
	{ 0x9221e043, __VMLINUX_SYMBOL_STR(snd_soc_register_codec) },
	{ 0x64e5299c, __VMLINUX_SYMBOL_STR(drm_gem_cma_prime_vmap) },
	{ 0x973c1054, __VMLINUX_SYMBOL_STR(of_node_put) },
	{ 0x40c57909, __VMLINUX_SYMBOL_STR(devm_kmalloc) },
	{ 0x7cf9099, __VMLINUX_SYMBOL_STR(wait_for_completion_timeout) },
	{ 0xb45a0b3c, __VMLINUX_SYMBOL_STR(snd_soc_register_card) },
	{ 0xae715e3c, __VMLINUX_SYMBOL_STR(drm_mode_object_unreference) },
	{ 0xe43d4594, __VMLINUX_SYMBOL_STR(devm_request_threaded_irq) },
	{ 0x771ff497, __VMLINUX_SYMBOL_STR(drm_atomic_helper_commit_modeset_enables) },
	{ 0xe8a17669, __VMLINUX_SYMBOL_STR(drm_mode_crtc_set_gamma_size) },
	{ 0xfb641168, __VMLINUX_SYMBOL_STR(mipi_dsi_host_register) },
	{ 0xe0329b37, __VMLINUX_SYMBOL_STR(drm_poll) },
	{ 0xc569d8ce, __VMLINUX_SYMBOL_STR(__clk_get_name) },
	{ 0x79d49618, __VMLINUX_SYMBOL_STR(drm_gem_cma_dumb_map_offset) },
	{ 0xb859f38b, __VMLINUX_SYMBOL_STR(krealloc) },
	{ 0x2e7a4300, __VMLINUX_SYMBOL_STR(drm_rgb_quant_range_selectable) },
	{ 0xcd244727, __VMLINUX_SYMBOL_STR(drm_open) },
	{ 0x75d98cb8, __VMLINUX_SYMBOL_STR(drm_atomic_helper_plane_destroy_state) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=drm,drm_kms_helper,snd-soc-core,snd-pcm";

MODULE_ALIAS("of:N*T*Cbrcm,bcm2835-vc4");
MODULE_ALIAS("of:N*T*Cbrcm,bcm2835-vc4C*");

MODULE_INFO(srcversion, "467CD6A738BEE54B27264EA");
